### ISSUE TITLE
这个sdk什么状况

### ISSUE THREAD

**Issue by ChinW** [longbai/swift-sdk#1]
可以拿来用吗

**Comment by longbai** [comment]
不好意思，只是挖了个坑，目前还没时间填上，十分抱歉。

**Comment by atjason** [comment]
汗，兴奋了半天集成到代码里，结果发现上传时没任何反应。到这里才发现是个坑。

话说，有计划支持 Swift 了吗？我是讲真。

**Comment by longbai** [comment]
手里的事情比较多，如果swift sdk OK的话会迁移到官方sdk，这一两个月吧。

**Comment by atjason** [comment]
好吧，目前老老实实桥接OC

同时，期待中

**Comment by alfredcc** [comment]
@longbai 加油，暂时只能自己先撸了
